/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beargame;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Douglas
 */
public class Cutscene extends javax.swing.JFrame {
    
    public final int LARGURA = 900; // Largura
    public final int ALTURA = 525; // Altura
    public final Dimension sizeGame = new Dimension(LARGURA, ALTURA);
    Image [] cutscene;

    /**
     * Creates new form Cutscene
     */
    public Cutscene() {
        initComponents();
        this.setSize(sizeGame);
        this.setPreferredSize(sizeGame);
        this.setMinimumSize(sizeGame);
        this.setResizable(false);
        
        btn_proximo.setOpaque(false);
        btn_proximo.setContentAreaFilled(false);
        btn_proximo.setBorderPainted(false);
        
        btn_voltar.setOpaque(false);
        btn_voltar.setContentAreaFilled(false);
        btn_voltar.setBorderPainted(false);
        cutscene = new Image [16];
        
        int cont;
        
        for (cont=0;cont<16;cont++){
            ImageIcon img_url = new javax.swing.ImageIcon(getClass().getResource("/res/cutscene/Cutscene_"+String.valueOf(cont+1)+".png"));
            Image image = img_url.getImage();  
            cutscene[cont] = image.getScaledInstance(900, 500, java.awt.Image.SCALE_SMOOTH);  
        }
        
        lbl_fundo.setIcon(new ImageIcon(cutscene[0]));
    }
    
    int controlador = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_proximo = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proximo(evt);
            }
        });
        getContentPane().add(btn_proximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 220, 40));

        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 443, 200, 50));

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cutscene/Cutscene_2.png"))); // NOI18N
        lbl_fundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Proximo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proximo
            controlador= controlador+1;
            if(controlador==16){
                MainMenu menu = new MainMenu();
                menu.setLocationRelativeTo(null);
                this.dispose();
                menu.setVisible(true);
            }
            else{
                lbl_fundo.setIcon(new ImageIcon(cutscene[controlador]));
                System.out.println("Direita");
            }
    }//GEN-LAST:event_Proximo

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        controlador= controlador-1;
        if(controlador==-1){
            MainMenu menu = new MainMenu();
            menu.setLocationRelativeTo(null);
            this.dispose();
            menu.setVisible(true);
        }
        else{
            lbl_fundo.setIcon(new ImageIcon(cutscene[controlador]));
            System.out.println("Esquerda");
        }
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cutscene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cutscene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cutscene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cutscene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cutscene().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel lbl_fundo;
    // End of variables declaration//GEN-END:variables
}
