/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beargame;

import java.awt.Dimension;
import java.awt.Image;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinny
 */
    public class Game extends javax.swing.JFrame {
    public final int LARGURA = 900; // Largura
    public final int ALTURA = 620; // Altura
    public final Dimension sizeGame = new Dimension(LARGURA, ALTURA);
    public BGParalaxe bg;
    Personagem ps;
    EnemyBird enemy;
    Sound sond;
    EnemyesControl ec;
    int enemy_speed=5;
    int enemy_move=1;
    public int life=100;
    boolean setlife=true;
    int energy=10;
    public int pontuacao=0;
    
    /**
     * Creates new form NewGame
     */
    public Game() {

        initComponents();
       
        // Definindo size do Game
        this.setSize(sizeGame);
        this.setPreferredSize(sizeGame);
        this.setMinimumSize(sizeGame);
        this.setResizable(false);
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
                
        // Constroi as classes das threads
        bg = new BGParalaxe(this);
        ps = new Personagem(this);
        ec=new EnemyesControl(this);
        
        // Starta as threads
        bg.start();
        ps.start();
        ec.start();
       
        // Adiciona a key listener de Personagem
        addKeyListener(ps);
        
        GameControl cg = new GameControl(this);
        cg.start();
        
        pb_energy.setValue(energy);
        teddy_life.setValue(life);
        
        // Adiciona foco no cenário para poder pegar ações do teclado
        this.setFocusable(true);
    }
    
    public void setLife(int set){
        if (setlife==true){
            setlife=false;

            int som=life+set;
            if (som>100){
                teddy_life.setValue(100);
                pb_energy.setValue(energy+=(som-100));
            } else {
                teddy_life.setValue(life+=set);
            }
        }
//        else {
//            setLife(set);
//        }
        setlife=true;
    }

    public void setEnergy(int value) {
        int en=energy+value;
        if(value>100){
            this.energy=100;
        } else {
            this.energy=en;
        }
        pb_energy.setValue(energy);
    }
    
    public void gameOver(){
        
        try {
            sleep(700);
        } catch (InterruptedException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         // Carregando imagem 
//        ImageIcon img_url = new javax.swing.ImageIcon(getClass().getResource("/res/vencedor.png"));
//        Image image = img_url.getImage();  
//        Image image_vencer = image.getScaledInstance(900, 510, java.awt.Image.SCALE_SMOOTH);
//        lbl_bg.setIcon(new ImageIcon(image_vencer));
//        lbl_bg.setBounds(0, 0, 900, 510);
        int op = JOptionPane.showConfirmDialog(this, "Tentar novamente ?");
        if (op==0){
            Game gg = new Game();
            gg.setLocationRelativeTo(null);
            this.dispose();
            gg.setVisible(true);
        } else {
            MainMenu mm = new MainMenu();
            mm.setLocationRelativeTo(null);
            this.dispose();
            mm.setVisible(true);
        }
        
//        JOptionPane.showMessageDialog(null, "Game Over");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_person = new javax.swing.JLabel();
        lbl_en_aviao = new javax.swing.JLabel();
        lbl_en_totem = new javax.swing.JLabel();
        lbl_en_bird = new javax.swing.JLabel();
        lbl_shot = new javax.swing.JLabel();
        jp_barra = new javax.swing.JPanel();
        lbl_pontuacao = new javax.swing.JLabel();
        teddy_life = new javax.swing.JProgressBar();
        pb_energy = new javax.swing.JProgressBar();
        lbl_barra = new javax.swing.JLabel();
        lbl_en_floco = new javax.swing.JLabel();
        lbl_floco_shot = new javax.swing.JLabel();
        lbl_nino = new javax.swing.JLabel();
        lbl_meteoro_vermelho = new javax.swing.JLabel();
        lbl_meteoro_azul = new javax.swing.JLabel();
        lbl_meteoro_roxo = new javax.swing.JLabel();
        lbl_escudo = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setTitle("Teddy Thug Life");
        getContentPane().setLayout(null);
        getContentPane().add(lbl_person);
        lbl_person.setBounds(90, 420, 0, 0);
        getContentPane().add(lbl_en_aviao);
        lbl_en_aviao.setBounds(810, 410, 80, 0);
        getContentPane().add(lbl_en_totem);
        lbl_en_totem.setBounds(810, 390, 80, 0);
        getContentPane().add(lbl_en_bird);
        lbl_en_bird.setBounds(810, 370, 80, 0);
        getContentPane().add(lbl_shot);
        lbl_shot.setBounds(170, 420, 0, 0);

        jp_barra.setBackground(new java.awt.Color(0, 102, 102));
        jp_barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jp_barra.add(lbl_pontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 70, 30));

        teddy_life.setBackground(new java.awt.Color(204, 255, 204));
        teddy_life.setForeground(new java.awt.Color(0, 51, 0));
        jp_barra.add(teddy_life, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, 30));
        teddy_life.getAccessibleContext().setAccessibleName("Life");
        teddy_life.getAccessibleContext().setAccessibleDescription("Life");

        pb_energy.setBackground(new java.awt.Color(204, 255, 204));
        pb_energy.setForeground(new java.awt.Color(0, 51, 0));
        jp_barra.add(pb_energy, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, 30));

        lbl_barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/barra.png"))); // NOI18N
        jp_barra.add(lbl_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jp_barra);
        jp_barra.setBounds(0, 470, 900, 130);
        getContentPane().add(lbl_en_floco);
        lbl_en_floco.setBounds(810, 430, 0, 0);
        getContentPane().add(lbl_floco_shot);
        lbl_floco_shot.setBounds(810, 380, 0, 0);
        getContentPane().add(lbl_nino);
        lbl_nino.setBounds(770, 200, 0, 0);
        getContentPane().add(lbl_meteoro_vermelho);
        lbl_meteoro_vermelho.setBounds(780, 130, 0, 0);
        getContentPane().add(lbl_meteoro_azul);
        lbl_meteoro_azul.setBounds(750, 170, 0, 0);
        getContentPane().add(lbl_meteoro_roxo);
        lbl_meteoro_roxo.setBounds(820, 170, 0, 0);
        getContentPane().add(lbl_escudo);
        lbl_escudo.setBounds(220, 390, 0, 0);

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bg_1.png"))); // NOI18N
        lbl_bg.setText("jLabel1");
        getContentPane().add(lbl_bg);
        lbl_bg.setBounds(0, 0, 5706, 510);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jp_barra;
    private javax.swing.JLabel lbl_barra;
    public javax.swing.JLabel lbl_bg;
    public javax.swing.JLabel lbl_en_aviao;
    public javax.swing.JLabel lbl_en_bird;
    public javax.swing.JLabel lbl_en_floco;
    public javax.swing.JLabel lbl_en_totem;
    public javax.swing.JLabel lbl_escudo;
    public javax.swing.JLabel lbl_floco_shot;
    public javax.swing.JLabel lbl_meteoro_azul;
    public javax.swing.JLabel lbl_meteoro_roxo;
    public javax.swing.JLabel lbl_meteoro_vermelho;
    public javax.swing.JLabel lbl_nino;
    public javax.swing.JLabel lbl_person;
    public javax.swing.JLabel lbl_pontuacao;
    public javax.swing.JLabel lbl_shot;
    public javax.swing.JProgressBar pb_energy;
    public javax.swing.JProgressBar teddy_life;
    // End of variables declaration//GEN-END:variables
}
