/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beargame;

/**
 *
 * @author Vinny
 */
public class Informations extends javax.swing.JFrame {

    /**
     * Creates new form Informations
     */
    public Informations() {
        initComponents();
        btn_infoback.setFocusable(false);
        
        btn_infoback.setOpaque(false);
        btn_infoback.setContentAreaFilled(false);
        btn_infoback.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_infoback = new javax.swing.JButton();
        lbl_back = new javax.swing.JLabel();
        lbl_infotitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teddy Thug Life");
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_infoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infobackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_infoback, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 13, 100, 40));

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Cutscene_back.png"))); // NOI18N
        getContentPane().add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, 60));

        lbl_infotitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Informações_menu.png"))); // NOI18N
        lbl_infotitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_infotitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_infobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infobackActionPerformed
        MainMenu menu = new MainMenu();
        menu.setLocationRelativeTo(null);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btn_infobackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_infoback;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_infotitle;
    // End of variables declaration//GEN-END:variables
}
