/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beargame;

import java.awt.Dimension;


/**
 *
 * @author Douglas
 */
public class MainMenu extends javax.swing.JFrame {
    public final int LARGURA = 900; // Largura
    public final int ALTURA = 520; // Altura
    public final Dimension sizeGame = new Dimension(LARGURA, ALTURA);
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        btn_historia.setFocusable(false);
        btn_new_game.setFocusable(false);
        btn_info.setFocusable(false);
        btn_ranking.setFocusable(false);
        btn_quit.setFocusable(false);
        this.setSize(sizeGame);
        this.setPreferredSize(sizeGame);
        this.setMinimumSize(sizeGame);
        this.setResizable(false);
        
        btn_new_game.setOpaque(false);
        btn_new_game.setContentAreaFilled(false);
        btn_new_game.setBorderPainted(false);
        
        btn_info.setOpaque(false);
        btn_info.setContentAreaFilled(false);
        btn_info.setBorderPainted(false);
        
        btn_ranking.setOpaque(false);
        btn_ranking.setContentAreaFilled(false);
        btn_ranking.setBorderPainted(false);
        
        btn_quit.setOpaque(false);
        btn_quit.setContentAreaFilled(false);
        btn_quit.setBorderPainted(false);
        
        btn_historia.setOpaque(false);
        btn_historia.setContentAreaFilled(false);
        btn_historia.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_new_game = new javax.swing.JButton();
        btn_ranking = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        btn_historia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teddy Thug Life");
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_new_game.setBackground(new java.awt.Color(255, 255, 255));
        btn_new_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_gameActionPerformed(evt);
            }
        });
        getContentPane().add(btn_new_game, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 80));

        btn_ranking.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rankingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, 80));

        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 270, 90));

        btn_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 280, 70));

        btn_historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historiaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Menu_Inicial_Completo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_new_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_gameActionPerformed
        Game game = new Game();
        game.setLocationRelativeTo(null);
        this.dispose();
        game.setVisible(true);
        
    }//GEN-LAST:event_btn_new_gameActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        Informations info = new Informations();
        info.setLocationRelativeTo(null);
        this.dispose();
        info.setVisible(true);
    }//GEN-LAST:event_btn_infoActionPerformed
        
    private void btn_rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rankingActionPerformed
        Ranking ranking = new Ranking();
        ranking.setLocationRelativeTo(null);
        this.dispose();
        ranking.setVisible(true);
    }//GEN-LAST:event_btn_rankingActionPerformed

    private void btn_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitActionPerformed

    private void btn_historiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historiaActionPerformed
        Cutscene historia = new Cutscene();
        historia.setLocationRelativeTo(null);
        this.dispose();
        historia.setVisible(true);
    }//GEN-LAST:event_btn_historiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_historia;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_new_game;
    private javax.swing.JButton btn_quit;
    private javax.swing.JButton btn_ranking;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
